<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>car_urdf</name>
  <version>2.1.0</version>
  <description>
    3D models of the car for simulation and visualization
  </description>
  <maintainer email="car@todo.todo">car</maintainer>
  <license>TODO: License declaration</license>
  <buildtool_depend>ament_cmake</buildtool_depend>
  <depend>urdf</depend>
  <depend>xacro</depend>
  <export>
    <build_type>ament_cmake</build_type>
    <gazebo_ros gazebo_model_path="/home/star/ros2_ws/install/car_urdf/share/car_urdf"/>
  </export>
</package>
